const loremIpsum = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum lorem venenatis ligula euismod, id mollis metus molestie. Duis fermentum sem ac est cursus volutpat. '

module.exports = [
	{
		id: 0,
		pictureUrl: require('./img/0_normal.jpg'),
		pictureUrlSmall: require('./img/0_small.jpg'),
		title: 'Sunny flat with view on the lake',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'rent',
		price: 750,
		area: 80,
		numRooms: 2,
		place: 'Barcelona',
		date: 1529160982
	},
	{
		id: 1,
		pictureUrl: require('./img/1_normal.jpg'),
		pictureUrlSmall: require('./img/1_small.jpg'),
		title: 'Spacious houses near the Grand-Place',
		description: loremIpsum,
		type: 'house',
		actionType: 'rent',
		price: 1800,
		area: 140,
		numRooms: 4,
		place: 'Bruxelles',
		date: 1529150982
	},
	{
		id: 2,
		pictureUrl: require('./img/2_normal.jpg'),
		pictureUrlSmall: require('./img/2_small.jpg'),
		title: 'Great appartment located in the heart of the city',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'rent',
		price: 800,
		area: 76,
		numRooms: 2,
		place: 'Barcelona',
		date: Date.now()
	},
	{
		id: 3,
		pictureUrl: require('./img/3_normal.jpg'),
		pictureUrlSmall: require('./img/3_small.jpg'),
		title: 'Traditionnal penthouse in the European neighborhood',
		description: loremIpsum,
		type: 'house',
		actionType: 'buy',
		price: 180000,
		area: 79,
		numRooms: 3,
		place: 'Bruxelles',
		date: 1529100982
	},
	{
		id: 4,
		pictureUrl: require('./img/4_normal.jpg'),
		pictureUrlSmall: require('./img/4_small.jpg'),
		title: 'Great flat right next to the main street',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'buy',
		price: 145000,
		area: 70,
		numRooms: 2,
		place: 'Bruxelles',
		date: 1528060982
	},
	{
		id: 5,
		pictureUrl: require('./img/5_normal.jpg'),
		pictureUrlSmall: require('./img/5_small.jpg'),
		title: 'Mediterranean villa in front of the sea',
		description: loremIpsum,
		type: 'house',
		actionType: 'buy',
		price: 270000,
		area: 102,
		numRooms: 4,
		place: 'Barcelona',
		date: 1516317131
	},
	{
		id: 6,
		pictureUrl: require('./img/6_normal.jpg'),
		pictureUrlSmall: require('./img/6_small.jpg'),
		title: 'Cosy flat all equiped',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'rent',
		price: 1250,
		area: 92,
		numRooms: 3,
		place: 'Bruxelles',
		date: 1509720385
	},
	{
		id: 7,
		pictureUrl: require('./img/7_normal.jpg'),
		pictureUrlSmall: require('./img/7_small.jpg'),
		title: 'Spacious appartment recently renovated',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'rent',
		price: 1100,
		area: 85,
		numRooms: 2,
		place: 'Bruxelles',
		date: 1443171851
	},
	{
		id: 8,
		pictureUrl: require('./img/8_normal.jpg'),
		pictureUrlSmall: require('./img/8_small.jpg'),
		title: 'Luminous flat perfect for a young family',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'rent',
		price: 950,
		area: 65,
		numRooms: 2,
		place: 'Barcelona',
		date: 1458271784
	},
	{
		id: 9,
		pictureUrl: require('./img/9_normal.jpg'),
		pictureUrlSmall: require('./img/9_small.jpg'),
		title: 'Renovated flat with a big living',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'buy',
		price: 210000,
		area: 86,
		numRooms: 3,
		place: 'Bruxelles',
		date: 1499081124
	},
	{
		id: 10,
		pictureUrl: require('./img/10_normal.jpg'),
		pictureUrlSmall: require('./img/10_small.jpg'),
		title: 'Futurist villa in th suburbs of Lilles',
		description: loremIpsum,
		type: 'house',
		actionType: 'buy',
		price: 440000,
		area: 178,
		numRooms: 5,
		place: 'Lilles',
		date: 1458448264
	},
	{
		id: 11,
		pictureUrl: require('./img/11_normal.jpg'),
		pictureUrlSmall: require('./img/11_small.jpg'),
		title: 'Ample houses by the sea',
		description: loremIpsum,
		type: 'house',
		actionType: 'rent',
		price: 1850,
		area: 99,
		numRooms: 3,
		place: 'Barcelona',
		date: 1505264625
	},
	{
		id: 12,
		pictureUrl: require('./img/12_normal.jpg'),
		pictureUrlSmall: require('./img/12_small.jpg'),
		title: 'Modern flat near the city centre',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'rent',
		price: 1450,
		area: 83,
		numRooms: 3,
		place: 'Lilles',
		date: 1457954580
	},
	{
		id: 13,
		pictureUrl: require('./img/13_normal.jpg'),
		pictureUrlSmall: require('./img/13_small.jpg'),
		title: 'Enormous house with a garden and veranda',
		description: loremIpsum,
		type: 'house',
		actionType: 'buy',
		price: 190000,
		area: 220,
		numRooms: 4,
		place: 'Helsinki',
		date: 1453491284
	},
	{
		id: 14,
		pictureUrl: require('./img/14_normal.jpg'),
		pictureUrlSmall: require('./img/14_small.jpg'),
		title: 'Recently renovated flat in Lilles',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'rent',
		price: 1200,
		area: 90,
		numRooms: 4,
		place: 'Lilles',
		date: 1507649692
	},
	{
		id: 15,
		pictureUrl: require('./img/15_normal.jpg'),
		pictureUrlSmall: require('./img/15_small.jpg'),
		title: 'Somptuous triplex in Bruxelles',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'rent',
		price: 3300,
		area: 170,
		numRooms: 4,
		place: 'Bruxelles',
		date: 1502773311
	},
	{
		id: 16,
		pictureUrl: require('./img/16_normal.jpg'),
		pictureUrlSmall: require('./img/16_small.jpg'),
		title: 'Cantina local for rent',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'rent',
		price: 2200,
		area: 130,
		numRooms: 2,
		place: 'Barcelona',
		date: 1502657235
	},
	{
		id: 17,
		pictureUrl: require('./img/17_normal.jpg'),
		pictureUrlSmall: require('./img/17_small.jpg'),
		title: 'Cosy little appartment for a couple',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'rent',
		price: 800,
		area: 62,
		numRooms: 1,
		place: 'Barcelona',
		date: 1449492604
	},
	{
		id: 18,
		pictureUrl: require('./img/18_normal.jpg'),
		pictureUrlSmall: require('./img/18_small.jpg'),
		title: 'Warm appartment in the heart of the city',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'rent',
		price: 1100,
		area: 71,
		numRooms: 2,
		place: 'Barcelona',
		date: 1470880574
	},
	{
		id: 19,
		pictureUrl: require('./img/19_normal.jpg'),
		pictureUrlSmall: require('./img/19_small.jpg'),
		title: 'Spacious living in Barcelona',
		description: loremIpsum,
		type: 'appartment',
		actionType: 'rent',
		price: 900,
		area: 68,
		numRooms: 2,
		place: 'Barcelona',
		date: 1504514435
	}
]